#ifndef _EMULATOR_COLORS_H
#define _EMULATOR_COLORS_H

typedef enum colors_e {
	COLOR_BLACK,
	COLOR_BLUE,
	COLOR_GREEN,
	COLOR_AQUA,
	COLOR_RED,
	COLOR_MAGENTA,
	COLOR_BROWN,
	COLOR_WHITE,
	COLOR_BRIGHT_BLACK,
	COLOR_BRIGHT_BLUE,
	COLOR_BRIGHT_LIME,
	COLOR_BRIGHT_AQUA,
	COLOR_BRIGHT_RED,
	COLOR_BRIGHT_MAGENTA,
	COLOR_BRIGHT_YELLOW,
	COLOR_BRIGHT_WHITE,
} colors_e;

#endif
