#ifndef _EMULATOR_OS_KBDPS2_H
#define _EMULATOR_OS_KBDPS2_H

#include "types.h"

typedef enum key_state_t {
	KEY_STATE_NULL,
	KEY_STATE_PRESSED,
	KEY_STATE_HOLDED,
	KEY_STATE_RELEASED
} key_state_t;

typedef enum scancode_e {
	SCANCODE_NULL,
	SCANCODE_ESCAPE,
	SCANCODE_1,
	SCANCODE_2,
	SCANCODE_3,
	SCANCODE_4,
	SCANCODE_5,
	SCANCODE_6,
	SCANCODE_7,
	SCANCODE_8,
	SCANCODE_9,
	SCANCODE_0,
	SCANCODE_MINUS_SIGN,
	SCANCODE_EQUAL,
	SCANCODE_BACKSPACE,
	SCANCODE_TAB,
	SCANCODE_Q,
	SCANCODE_W,
	SCANCODE_E,
	SCANCODE_R,
	SCANCODE_T,
	SCANCODE_Y,
	SCANCODE_U,
	SCANCODE_I,
	SCANCODE_O,
	SCANCODE_P,
	SCANCODE_LEFT_BRACKET,
	SCANCODE_RIGHT_BRACKET,
	SCANCODE_ENTER,
	SCANCODE_CONTROL,
	SCANCODE_A,
	SCANCODE_S,
	SCANCODE_D,
	SCANCODE_F,
	SCANCODE_G,
	SCANCODE_H,
	SCANCODE_J,
	SCANCODE_K,
	SCANCODE_L,
	SCANCODE_SEMICOLON,
	SCANCODE_QUOTE,
	SCANCODE_BACK_TICK,
	SCANCODE_LEFT_SHIFT,
	SCANCODE_BACKSLASH,
	SCANCODE_Z,
	SCANCODE_X,
	SCANCODE_C,
	SCANCODE_V,
	SCANCODE_B,
	SCANCODE_N,
	SCANCODE_M,
	SCANCODE_COMMA,
	SCANCODE_DOT,
	SCANCODE_SLASH,
	SCANCODE_RIGHT_SHIFT,
	SCANCODE_NUMBER_PAD_ASTERISK,
	SCANCODE_LEFT_ALT,
	SCANCODE_SPACE,
	SCANCODE_CAPSLOCK,
	SCANCODE_F1,
	SCANCODE_F2,
	SCANCODE_F3,
	SCANCODE_F4,
	SCANCODE_F5,
	SCANCODE_F6,
	SCANCODE_F7,
	SCANCODE_F8,
	SCANCODE_F9,
	SCANCODE_F10,
	SCANCODE_NUMBER_PAD_LOCK,
	SCANCODE_SCROLL_LOCK,
	SCANCODE_NUMBER_PAD_7,
	SCANCODE_NUMBER_PAD_8,
	SCANCODE_NUMBER_PAD_9,
	SCANCODE_NUMBER_PAD_MINUS_SIGN,
	SCANCODE_NUMBER_PAD_4,
	SCANCODE_NUMBER_PAD_5,
	SCANCODE_NUMBER_PAD_6,
	SCANCODE_NUMBER_PAD_PLUS_SIGN,
	SCANCODE_NUMBER_PAD_1,
	SCANCODE_NUMBER_PAD_2,
	SCANCODE_NUMBER_PAD_3,
	SCANCODE_NUMBER_PAD_0,
	SCANCODE_NUMBER_PAD_DOT,
	SCANCODE_NONE0,
	SCANCODE_NONE1,
	SCANCODE_NONE2,
	SCANCODE_F11,
	SCANCODE_F12,
	SCANCODE_EXTENDED = 0xE0
} scancode_e;

typedef enum ext_scancode_e {
	EXT_SCANCODE_ARROW_UP = 72, 
	EXT_SCANCODE_ARROW_LEFT = 75,
	EXT_SCANCODE_ARROW_RIGHT = 77,
	EXT_SCANCODE_ARROW_DOWN = 80,
} ext_scancode_e;

void kbdps2_init();

byte getch();

byte* getstr(bool show);

byte* getstr_hist(bool show, byte history[][64], ssize_t* command_index, size_t history_len);

void kbdps2_deinit();

#endif
