#ifndef _EMULATOR_KBDPS2_H
#define _EMULATOR_KBDPS2_H

#include "types.h"

#define INPUT_BUFFER_MAX_SIZE 128

typedef struct kbdps2_t {
	byte pressed_key[4];
} kbdps2_t;

// " ", "☺", "☻", "♥", "♦", "♣", 
// 	"♠", "•", "◘", "○", "◙", "♂", 
// 	"♀", "♪", "♫", "☼", "►", "◄", 
// 	"↕", "‼", "¶", "§", "▬", "↨", 
// 	"↑", "↓", "→", "←", "∟", "↔", 
// 	"▲", "▼", " ", "!", "\"", "#", 
// 	"$", "%", "&", "\'", "(", ")", 
// 	"*", "+", ",", "-", ".", "/", 
// 	"0", "1", "2", "3", "4", "5", 
// 	"6", "7", "8", "9", ":", ";", 
// 	"<", "=", ">", "?", "@", "A", 
// 	"B", "C", "D", "E", "F", "G", 
// 	"H", 
// 	"I", "J", "K", "L", "M", "N", 
// 	"O", "P", "Q", "R", "S", "T", 
// 	"U", "V", "W", "X", "Y", "Z", 
// 	"[", "\\", "]", "^", "_", "`", 
// 	"a", 
// 	"b", "c", "d", "e", "f", "g", 
// 	"h", "i", "j", "k", "l", "m", 
// 	"n", "o", "p", "q", "r", "s", 
// 	"t", "u", "v", "w", "x", "y", 
// 	"z", "{", "¦", "}", "~",
// 	"⌂", "Ç", "ü", "é", "â", "ä", 
// 	"à", "å", "ç", "ê", "ë", "è", 
// 	"ï", "î", "ì", "Ä", "Å", "É", 
// 	"æ", "Æ", "ô", "ö", "ò", "û", 
// 	"ù", "ÿ", "Ö", "Ü", "¢", "£", 
// 	"¥", "₧", "ƒ", "á", "í", "ó", 
// 	"ú", "ñ", "Ñ", "ª", "º", "¿", 
// 	"⌐", "¬", "½", "¼", "¡", "«", 
// 	"»", "░", "▒", "▓", "│", "┤", 
// 	"╡", "╢", "╖", "╕", "╣", "║", 
// 	"╗", "╝", "╜", "╛", "┐", "└", 
// 	"┴", "┬", "├", "─", "┼", "╞", 
// 	"╟", "╚", "╔", "╩", "╦", "╠", 
// 	"═", "╬", "╧", "", "╨", "╤", 
// 	"╥", "╙", "╘", "╒", "╓", "╫", 
// 	"╪", "┘", "┌", "█", "▄", "▌", 
// 	"▐", "▀", "α", "ß", "Γ", "π", 
// 	"Σ", "σ", "µ", "τ", "Φ", "Θ", 
// 	"Ω", "δ", "∞", "φ", "ε", "∩", 
// 	"≡", "±", "≥", "≤", "⌠", "⌡", 
// 	"÷", "≈", "°", "∙", "·", "√", 
// 	"ⁿ", "²", "■", " "

typedef enum scancode_e {
	SCANCODE_NULL,
	SCANCODE_ESCAPE,
	SCANCODE_1,
	SCANCODE_2,
	SCANCODE_3,
	SCANCODE_4,
	SCANCODE_5,
	SCANCODE_6,
	SCANCODE_7,
	SCANCODE_8,
	SCANCODE_9,
	SCANCODE_0,
	SCANCODE_MINUS_SIGN,
	SCANCODE_EQUAL,
	SCANCODE_BACKSPACE,
	SCANCODE_TAB,
	SCANCODE_Q,
	SCANCODE_W,
	SCANCODE_E,
	SCANCODE_R,
	SCANCODE_T,
	SCANCODE_Y,
	SCANCODE_U,
	SCANCODE_I,
	SCANCODE_O,
	SCANCODE_P,
	SCANCODE_LEFT_BRACKET,
	SCANCODE_RIGHT_BRACKET,
	SCANCODE_ENTER,
	SCANCODE_CONTROL,
	SCANCODE_A,
	SCANCODE_S,
	SCANCODE_D,
	SCANCODE_F,
	SCANCODE_G,
	SCANCODE_H,
	SCANCODE_J,
	SCANCODE_K,
	SCANCODE_L,
	SCANCODE_SEMICOLON,
	SCANCODE_QUOTE,
	SCANCODE_BACK_TICK,
	SCANCODE_LEFT_SHIFT,
	SCANCODE_BACKSLASH,
	SCANCODE_Z,
	SCANCODE_X,
	SCANCODE_C,
	SCANCODE_V,
	SCANCODE_B,
	SCANCODE_N,
	SCANCODE_M,
	SCANCODE_COMMA,
	SCANCODE_DOT,
	SCANCODE_SLASH,
	SCANCODE_RIGHT_SHIFT,
	SCANCODE_NUMBER_PAD_ASTERISK,
	SCANCODE_LEFT_ALT,
	SCANCODE_SPACE,
	SCANCODE_CAPSLOCK,
	SCANCODE_F1,
	SCANCODE_F2,
	SCANCODE_F3,
	SCANCODE_F4,
	SCANCODE_F5,
	SCANCODE_F6,
	SCANCODE_F7,
	SCANCODE_F8,
	SCANCODE_F9,
	SCANCODE_F10,
	SCANCODE_NUMBER_PAD_LOCK,
	SCANCODE_SCROLL_LOCK,
	SCANCODE_NUMBER_PAD_7,
	SCANCODE_NUMBER_PAD_8,
	SCANCODE_NUMBER_PAD_9,
	SCANCODE_NUMBER_PAD_MINUS_SIGN,
	SCANCODE_NUMBER_PAD_4,
	SCANCODE_NUMBER_PAD_5,
	SCANCODE_NUMBER_PAD_6,
	SCANCODE_NUMBER_PAD_PLUS_SIGN,
	SCANCODE_NUMBER_PAD_1,
	SCANCODE_NUMBER_PAD_2,
	SCANCODE_NUMBER_PAD_3,
	SCANCODE_NUMBER_PAD_0,
	SCANCODE_NUMBER_PAD_DOT,
	SCANCODE_NONE0,
	SCANCODE_NONE1,
	SCANCODE_NONE2,
	SCANCODE_F11,
	SCANCODE_F12,
	SCANCODE_CONTROL_SEQUENCE = 0xE0
} scancode_e;

void handle_key_gui(byte sdl_scancode, bool is_key_released);

void handle_keys_cli();

kbdps2_t* init_kbdps2(bool gui);

void free_kbdps2(kbdps2_t* kbdps2);

void reset_kbdps2(kbdps2_t* kbdps2);

void release_all_kbdps2();

#endif
