#ifndef _EMULATOR_OS_BLOCK_STD_H
#define _EMULATOR_OS_BLOCK_STD_H

#define set_cursor_pos 0
#define get_terminal_size 0

#define get_draw_buf 0

#define set_halt 0

#define clear_halt 0

#define init_default_table_port_in 0

#define isalnum 0
#define isalpha 0
#define isblank 0
#define iscntrl 0
#define isdigit 0
#define isgraph 0
#define islower 0
#define isprint 0
#define ispunct 0
#define isspace 0
#define isupper 0
#define isxdigit 0
#define tolower 0
#define toupper 0
#define acos 0
#define asin 0
#define atan 0
#define atan2 0
#define cos 0
#define sin 0
#define tan 0
#define cosh 0
#define sinh 0
#define tanh 0
#define exp 0
#define frexp 0
#define ldexp 0
#define log 0
#define log10 0
#define modf 0
#define pow 0
#define sqrt 0
#define ceil 0
#define fabs 0
#define floor 0
#define fmin 0
#define fmax 0
#define fmod 0
#define acosf 0
#define asinf 0
#define atanf 0
#define atan2f 0
#define cosf 0
#define sinf 0
#define tanf 0
#define coshf 0
#define sinhf 0
#define tanhf 0
#define expf 0
#define frexpf 0
#define ldexpf 0
#define logf 0
#define log10f 0
#define modff 0
#define powf 0
#define sqrtf 0
#define ceilf 0
#define fabsf 0
#define floorf 0
#define fmodf 0
#define remove 0
#define rename 0
#define tmpfile 0
#define tmpnam 0
#define fclose 0
#define fflush 0
#define fopen 0
#define freopen 0
#define setbuf 0
#define setvbuf 0
#define fprintf 0
#define fscanf 0
#define printf 0
#define scanf 0
#define snprintf 0
#define sprintf 0
#define sscanf 0
#define vfprintf 0
#define vfscanf 0
#define vprintf 0
#define vscanf 0
#define vsnprintf 0
#define vsprintf 0
#define vsscanf 0
#define fgetc 0
#define fgets 0
#define fputc 0
#define fputs 0
#define getc 0
#define getchar 0
#define gets 0
#define putc 0
#define putchar 0
#define puts 0
#define ungetc 0
#define fread 0
#define fwrite 0
#define fgetpos 0
#define fseek 0
#define fsetpos 0
#define ftell 0
#define rewind 0
#define clearerr 0
#define feof 0
#define ferror 0
#define perror 0
#define atof 0
#define atoi 0
#define atol 0
#define strtod 0
#define strtol 0
#define strtoul 0
#define rand 0
#define srand 0
#define calloc 0
#define free 0
#define malloc 0
#define realloc 0
#define abort 0
#define atexit 0
#define exit 0
#define getenv 0
#define system 0
#define bsearch 0
#define qsort 0
#define abs 0
#define div 0
#define labs 0
#define ldiv 0
#define memcpy 0
#define memmove 0
#define strcpy 0
#define strncpy 0
#define strcat 0
#define strncat 0
#define memcmp 0
#define strcmp 0
#define strcoll 0
#define strncmp 0
#define strxfrm 0
#define memchr 0
#define strchr 0
#define strcspn 0
#define strpbrk 0
#define strrchr 0
#define strspn 0
#define strstr 0
#define strtok 0
#define memset 0
#define strerror 0
#define strlen 0
#define clock 0
#define difftime 0
#define mktime 0
#define time 0
#define asctime 0
#define ctime 0
#define gmtime 0
#define localtime 0
#define strftime 0
#define setlocale 0
#define localeconv 0
#define setjmp 0
#define longjmp 0
#define signal 0
#define raise 0
#define va_start 0
#define va_arg 0
#define va_end 0
#define wcscat 0
#define wcschr 0
#define wcscmp 0
#define wcscpy 0
#define wcscspn 0
#define wcslen 0
#define wcsncat 0
#define wcsncmp 0
#define wcsncpy 0
#define wcspbrk 0
#define wcsrchr 0
#define wcsspn 0
#define wcsstr 0
#define wcstok 0

#define read 0
#define write 0
#define close 0
#define lseek 0
#define pipe 0
#define dup 0
#define dup2 0
#define access 0
#define unlink 0

#define fork 0
#define exec 0
#define execl 0
#define execv 0
#define getpid 0
#define getppid 0
#define getuid 0
#define geteuid 0
#define getgid 0
#define getegid 0
#define setuid 0
#define setgid 0

#define chdir 0
#define getcwd 0
#define rmdir 0
#define chown 0
#define link 0
#define symlink 0

#define sleep 0
#define usleep 0
#define alarm 0

#define gethostname 0
#define sysconf 0

#endif